# Generated by Django 3.2.16 on 2022-11-10 15:48

import api.utils.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imageaws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to=api.utils.image_utils.rename_image)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
